buildserver:
	GOOS=js GOARCH=wasm go build -o output/autogenerated/simastericsgen.wasm cmd/simastericsgen-server/assets/simastericsgen.go
	go build -o output/simastericsgen-server cmd/simastericsgen-server/main.go
	cp cmd/simastericsgen-server/assets/index.html output/
	cp $$(go env GOROOT)/misc/wasm/wasm_exec.js output/autogenerated

buildcli:
	go build -o output/simastericsgen cmd/simastericsgen/main.go

test:
	go test -v $$(go list ./... | grep -v /assets)

clean:
	rm -rf output
