name: Test and build SimasterICSGen
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go test and build
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.1'
      - run: make test
      - run: make buildcli
